### ISSUE TITLE
Add support for refclock devices

### ISSUE THREAD

**Issue by Klaas-** [linux-system-roles/timesync#114]
Hi,
Azure (HyperV) is providing a device that can be used to time synchronization. We would like to incorporate this into our configuration.

`refclock PHC /dev/ptp0 poll 3 dpoll -2 offset 0`
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync#chrony

It would be nice if this role could automatically detect these devices and use them or at least provide a parameter for usage.

Greetings
Klaas

**Comment by mlichvar** [comment]
I think this is a good use case for the new `chrony_custom_settings` variable. An automatic detection would be problematic, becase the guest doesn't know if the host actually has the system clock synchronized.

**Comment by Klaas-** [comment]
Hi, I did not see I could use the custom setting for this type of setting. That is sufficient for my immediate needs. Thank you for that hint.

For automatic detection part -- yes I agree, it is not ensured that the hypervisor has a synchronized clock. But this is a totally different problem category -- I mean you don't ensure that a server (as in timesync_ntp_servers) used in the timesync configuration has a proper time either, right? You just expect that if you offer that service the clock is also properly synchronized :) In my current use case the device will (at least for now) just be another clock source next to the ntp servers. But I could see myself disabling the ntp servers in a restricted-network type scenario.

**Comment by mlichvar** [comment]
If you specify a server, you expect it to be synchronized. Same could be said about specifying a /dev/ptp* device. But configuring it automatically, just by its presence, I think would create an implicit assumption that all PTP clocks in VMs are synchronized. They don't have to be. It depends on the configuration of the host, which the guest doesn't see.

Anyway, thanks for the update. I'll close this issue.
