### ISSUE TITLE
{{ ansible_managed | comment }}

### ISSUE THREAD

**Issue by xenobiot** [linux-system-roles/timesync#123]
Hello,

at the [template files](https://github.com/linux-system-roles/timesync/tree/master/templates) you are using **# {{ ansible_managed }}**.
In the  [Ansible documentation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#manipulating-text) is described how to distribute **ansible_managed** to several lines for better readability. 

It can be done by **{{ ansible_managed | comment }}**.

Could you please adapt the template files from **# {{ ansible_managed }}** to **{{ ansible_managed | comment }}**?

Thank you very much. 

Best regards

**Comment by spetrosi** [comment]
Hello @xenobiot, thank you for your feedback. 

I am checking the `/etc/chrony.conf` file. 
When the template uses the current `# {{ ansible_managed }}`, the file builds as follows:
```
[root@fedora ~]# cat /etc/chrony.conf
# Ansible managed

server <output ommited>...
```
When the template uses `{{ ansible_managed | comment }}` as you suggested, the file builds as follows:
```
[root@fedora ~]# cat /etc/chrony.conf
#
# Ansible managed
#

server <output ommited>...
```
That's not much of a difference, can you share an example where using `{{ ansible_managed | comment }}` is more useful? Does the current `# {{ ansible_managed }}` break any config files?

Thank you

**Comment by xenobiot** [comment]
Hello spetrosi,

thanks for your quick reply.

My ansible_managed variable looks like this (it's not just one line):
```shell
user@ansiblemaster:~# cat ansible.cfg|grep -A 4 ansible_managed
ansible_managed = WARNING: This file is managed by ANSIBLE.
  template: {file}
  modified on: %Y-%m-%d %H:%M:%S
  by user: {uid}
  from ansiblemaster: {host}
```

If I'm using **{{ ansible_managed | comment }}** it will result in:
```shell
root@managedserver:~# cat /etc/auto.master.d/software.autofs
#
# WARNING: This file is managed by ANSIBLE.
# template: /path/to/my/ansible/roles/myrole/templates/RedHat_8/software.autofs
# modified on: 2021-09-15 13:52:13
# by user: root
# from ansiblemaster: ansiblemaster.mydomain.com
#
/-     /etc/auto.software
```
Otherwise (**# {{ ansible_managed }}**) it will comment just the first line, which will result in an error when chronyd.service is reading the file:
```shell
root@andrea2:~# cat /etc/chrony.conf
# WARNING: This file is managed by ANSIBLE.
template: /usr/share/ansible/roles/rhel-system-roles.timesync/templates/chrony.conf.j2
modified on: 2021-09-15 13:35:58
by user: root
from ansiblemaster: ansiblemaster.mydomain.com
```
**{{ ansible_managed | comment }}** seems to be fine for ansible_managed with one and multi lines.
We choose the multiline version for better readability.

By the way:
'#' is the default. In case you need another sign (e.g. " instead of #) for comment out you can use:
**{{ ansible_managed | comment(decoration='" ') }}**

Could you please check this and if you think it is good, adjust it?

Thank you very much. 

Best regards

**Comment by spetrosi** [comment]
Thank you for the details. Indeed, the additional uncommented lines at the top of the config file like in your example cause the `chrony` service to fail to start. I'll prioritize this.
