### ISSUE TITLE
RFE: Add option for noselect to the timesync_ntp_servers options

### ISSUE THREAD

**Issue by chsnell** [linux-system-roles/timesync#191]
noselect is a valid option for server & pool entries for both chronyd and ntpd.  It has usefulness when you want to have a reference clock available but not utilized as a synchronization option such as in a tightly controlled network.  It would be a boolean value, much the same as pool or nts.

**Comment by chsnell** [comment]
There is already a timesync_chrony_custom_settings which would allow it for chrony, but you would have to enter a whole line with all the settings such as:

server foo.example.com maxpoll 12 noselect

Based on the template code currently, this would add an additional entry all the way at the end of the file rather than cleanly with the rest of the server/poll lines.

I just happen to need the noselect in my configuration, but ideally I could see the code eventually being extended to support most if not all of the server/pool options to allow the role to be more fully featured.

**Comment by richm** [comment]
> There is already a timesync_chrony_custom_settings which would allow it for chrony, but you would have to enter a whole line with all the settings such as:
> 
> server foo.example.com maxpoll 12 noselect
> 
> Based on the template code currently, this would add an additional entry all the way at the end of the file rather than cleanly with the rest of the server/poll lines.

I don't understand - is the order of these items significant?  And if the file is being generated by the timesync role, why does the file need to be "clean"?

> 
> I just happen to need the noselect in my configuration, but ideally I could see the code eventually being extended to support most if not all of the server/pool options to allow the role to be more fully featured.
