### ISSUE TITLE
Errors in check mode

### ISSUE THREAD

**Issue by hhaniel** [linux-system-roles/timesync#27]
I am playing with this module for the first time - still slightly inexperienced with ansible but following the instructions and hitting a wall generating ntp.conf

TASK [linux-system-roles.timesync : Generate ntp.conf file] ********************************************
fatal: [tumbleweed-x]: FAILED! => {"changed": false, "msg": "AnsibleFilterError: Version comparison: 'dict object' has no attribute 'stdout'"}

I am trying to get the basics to work and then looking at modifying this role/module to incorporate settings for timekeeper. - I am also looking for options to use this on SLES if possible.

**Comment by hairmare** [comment]
Are you running Ansible with `--check`? I think this error gets thrown if any of the values in `templates/ntp.conf.j2` that should get `register`ed by an earlier skipped task.

I think it's this task that is being skipped in check mode.

https://github.com/linux-system-roles/timesync/blob/d55dd3ebd7f39a390a492061ab7d4d6b5fb87936/tasks/main.yml#L59-L65

And this line of the template that would like to use the variable and then proceeds to throw a semi-helpful error message (the stuff about "Version comparison" gave me the hint).

https://github.com/linux-system-roles/timesync/blob/d55dd3ebd7f39a390a492061ab7d4d6b5fb87936/templates/ntp.conf.j2#L16

Does it work if you run it without `--check`?

**Comment by hhaniel** [comment]
OK - this seems to have been the issue - I have added a "check_mode: no" in that paragraph so now I can run the whole role in check mode as well. In our environment we need to be able to run everything in check  mode. Many Thanx

**Comment by pcahyna** [comment]
@hhaniel what paragraph do you mean, the "Get ntp version" task? We could add the `check_mode: no` option. So far we have not tested linux-system-roles for proper check mode support, but we might start in order to help cases like yours.

**Comment by hhaniel** [comment]
I have added it in line 65:

 59 - name: Get ntp version
 60   command: rpm -q --qf '%{version}' ntp
 61   args:
 62     warn: no
 63   register: timesync_ntp_version
 64   changed_when: False
 65   check_mode: no
 66   when: timesync_mode != 2 and timesync_ntp_provider == 'ntp'


If you could modify this from your side that would be great since we would like to stick to the core code rather then branching it in our environment.

**Comment by hhaniel** [comment]
The same goes by the way for the chrony version check - I had to do the same there.

**Comment by pcahyna** [comment]
> The same goes by the way for the chrony version check - I had to do the same there.

Yeah, there will be multiple instances of this problem, and in the other roles as well.

**Comment by hhaniel** [comment]
[main.yml.gz](https://github.com/linux-system-roles/timesync/files/2962094/main.yml.gz)


Consider above attached main.yml file - I have made modifications to it so it can run cleanly in check mode and in apply mode. So it checks if certain rpm's are installed before services are enabled or disabled. If a service is not installed (like linuxptp) the specific tasks for them are skipped where they may cause an error or in check mode they will come back as changed even though nothing has changed.

I have only tested this with installing NTP in anger as we do not use any of the other services in our environment yet.

**Comment by pcahyna** [comment]
Hi @hhaniel , thanks for your contribution. I thought that we fixed the check mode issues, but now I see that your change fixes one case that still is not working properly: the case when the role has not been applied previously, and therefore packages assumed to exist are missing. I've opened #51 to track this.
