### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by hhaniel** [linux-system-roles/timesync#29]
The following warning is displayed at several places if I turn the warnings on:

[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|version_compare` use `result is version_compare`. This feature will be
removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

I suppose that is a fairly simple fix.

**Comment by pcahyna** [comment]
PR #23 was supposed to fix it. @vcrhonek could you please double check the role whether there are more instances of this problem lingering?

**Comment by vcrhonek** [comment]
> PR #23 was supposed to fix it. @vcrhonek could you please double check the role whether there are more instances of this problem lingering?

That's correct, PR #23 fixes the issue.

**Comment by pcahyna** [comment]
Hi, the fix is released in version 1.0.2, which is available from Galaxy.
