### ISSUE TITLE
Tests on rhel-7 are failing

### ISSUE THREAD

**Issue by pcahyna** [linux-system-roles/timesync#5]
See the CI results on #3. Note that the PR did not change anything relevant AFAICT and it merely triggered a test run. The error is "No package matching 'linuxptp' found available, installed or updated". The same error was already noted in the last comment on #1.

Surprisingly, the tests pass for CentOS 7.

**Comment by mlichvar** [comment]
As we found out, the issue is not in the role, but in the rhel images used for testing. They don't have any repositories configured from which could be installed linuxptp and other packages installed by the role.

**Comment by pcahyna** [comment]
this should be addressed now, the updated test-harness does register yum repositories in the test VMs

**Comment by pcahyna** [comment]
there is code in https://github.com/linux-system-roles/test-harness/pull/26 to run arbitrary Ansible plays and the CI configuration was updated to take advantage of this to update the yum configuration

**Comment by pcahyna** [comment]
tests are passing now, see e.g. #9. Closing.
