### ISSUE TITLE
time sync is not working using the rhel system roles on managed nodes, please help!!!

### ISSUE THREAD

**Issue by naveen21a** [linux-system-roles/timesync#58]
#  vim  timesynchro.yml
---
- hosts: all
   vars:
    timesync_ntp_servers:
      - hostname:  10.26.xx.xx
        iburst:  yes
  roles:
   - rhel-system-roles.timesync

**Comment by naveen21a** [comment]
Please note that there are no error messages after the code execution. time sync is not working on the managed nodes!

**Comment by mlichvar** [comment]
What does `chronyc -n sources` or `ntpq -pn` print?

**Comment by richm** [comment]
Can you provide steps for us to reproduce e.g. exact platforms/versions of ansible you used to run ansible; os and versions of managed nodes; exact ansible-playbook command line; playbooks you used or excerpts thereof; version of the timesync role, and where you used it from (e.g. ansible galaxy, or from this github directly); any logs or other output we can use to diagnose the problem.

**Comment by richm** [comment]
Please reopen or file another issue if you can reproduce
