### ISSUE TITLE
Use service_facts instead of chkconfig/systemctl

### ISSUE THREAD

**Issue by richm** [linux-system-roles/timesync#81]
The role uses `chkconfig` https://github.com/linux-system-roles/timesync/blob/master/tasks/setup/RedHat_6.yml and `systemctl list-unit-files` https://github.com/linux-system-roles/timesync/blob/master/tasks/setup/default.yml to get a list of services on the system.  Instead, the role should use https://docs.ansible.com/ansible/latest/modules/service_facts_module.html if possible.  @pavel-z1 fyi @pcahyna @mlichvar

**Comment by pavel-z1** [comment]
Thank you @richm 
I've created PR.

**Comment by richm** [comment]
fixed in https://github.com/linux-system-roles/timesync/pull/84
