### ISSUE TITLE
Suggestion: configure timezone

### ISSUE THREAD

**Issue by Thulium-Drake** [linux-system-roles/timesync#94]
I consider configuring a timezone to be part of making sure the system displays the correct time.

Do you guys agree? If so, I can make a PR that will implement it :-)

**Comment by mlichvar** [comment]
I don't think that is related to synchronization of clocks. NTP uses UTC. PTP uses UTC or TAI. There are no timezones involved.

**Comment by Thulium-Drake** [comment]
You make a fair point! In that case, I will configure that with Ansible in a different manner.
